---
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "unusedcode,codesize,naming,design,cleancode"
    Naming/ShortVariable:
      enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
exclude_paths: []
