<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClaseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function finAllEstados()
    {
        return $this
            ->createQueryBuilder('clases')
            ->distinct('estado')
            ->getQuery()->getResult()
        ;
    }

    /**
     * @param array $criteria
     *
     * @return array
     */
    public function findRangoClases(array $criteria)
    {
        return $this
            ->createQueryBuilder('clases')
            ->where('clases.fecha_inicio BETWEEN :fecha_inicio and :fecha_fin')
            ->orWhere('clases.fecha_fin BETWEEN :fecha_inicio and :fecha_fin')
            ->andWhere('clases.lugar = :lugar')
            ->setParameters($criteria)
            ->getQuery()->getResult()
        ;
    }
}
