<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClaseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function finAllEstados()
    {
        return $this
            ->createQueryBuilder('clases')
            ->distinct('estado')
            ->getQuery()->getResult()
        ;
    }

    /**
     * @param array $criteria
     *
     * @return array
     */
    public function findRangoClase(array $criteria)
    {
        return $this
            ->createQueryBuilder('clases')
            ->where(':horaInicio BETWEEN clases.horaInicio AND clases.horaFin')
            ->orWhere(':horaFin BETWEEN clases.horaInicio AND clases.horaFin')
            ->andWhere('clases.lugar = :lugar')
            ->andWhere('clases.fecha = :fecha')
            ->setParameters($criteria)
            ->getQuery()->getResult()
        ;
    }
}
