<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClaseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaseRepository extends EntityRepository
{
    /**
     * @param array $criteria
     *
     * @return array
     */
    public function findRangoClase(array $criteria)
    {
        return $this
            ->createQueryBuilder('clases')
            ->where(':horaInicio >= clases.horaInicio AND :horaInicio < clases.horaFin')
            ->orWhere(':horaFin > clases.horaInicio AND :horaFin <= clases.horaFin')
            ->andWhere('clases.lugar = :lugar')
            ->andWhere('clases.fecha = :fecha')
            ->setParameters($criteria)
            ->getQuery()->getResult()
        ;
    }
}
