<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClaseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function finAllEstados()
    {
        return $this
            ->createQueryBuilder('eventos')
            ->distinct('estado')
            ->getQuery()->getResult()
        ;
    }

    public function findRangoEventos(array $criteria)
    {
        return $this
            ->createQueryBuilder('eventos')
            ->where('eventos.fecha_inicio BETWEEN :fecha_inicio and :fecha_fin')
            ->orWhere('eventos.fecha_fin BETWEEN :fecha_inicio and :fecha_fin')
            ->andWhere('eventos.lugar = :lugar')
            ->setParameters($criteria)
            ->getQuery()->getResult()
        ;
    }
}
