<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LugarRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarRepository extends EntityRepository
{
    public function finAllVisibles()
    {
        return $this
            ->createQueryBuilder('lugares')
            ->where('lugares.visible = 1')
            ->orderBy('lugares.nombre', 'ASC')
            ->getQuery()->getResult();
    }
}