<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrestamoPracticaLibreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestamoPracticaLibreRepository extends EntityRepository
{
    /**
     * @param array $criteria
     *
     * @return array
     */
    public function findPrestamosRango(array $criteria)
    {
        return $this
            ->createQueryBuilder('prestamos')
            ->select('MONTH(prestamos.fechaPrestamo) AS mes, COUNT(prestamos.id) AS total')
            ->where(':anio = YEAR(prestamos.fechaPrestamo)')
            ->andWhere('MONTH(prestamos.fechaPrestamo) BETWEEN :mesInicio AND :mesFin')
            ->groupBy('mes')
            ->setParameters($criteria)
            ->getQuery()->getResult()
        ;
    }

    /**
     * @param array $criteria
     *
     * @return array
     */
    public function findPrestamosMes(array $criteria)
    {
        return $this
            ->createQueryBuilder('prestamos')
            ->select('DAY(prestamos.fechaPrestamo) AS dia, COUNT(prestamos.id) AS total')
            ->where(':mes = MONTH(prestamos.fechaPrestamo)')
            ->groupBy('dia')
            ->setParameters($criteria)
            ->getQuery()->getResult()
            ;
    }
}
