<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrestamoPracticaLibreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestamoPracticaLibreRepository extends EntityRepository
{
}
