<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectoCurricularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoCurricularRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllFacultades()
    {
        return $this
            ->createQueryBuilder('proyectocurricular')
            ->distinct('facultad')
            ->getQuery()->getResult()
            ;
    }
}
