<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrasladoElementoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrasladoElementoRepository extends EntityRepository
{
}
