imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    list:
        actions:
            - { name: 'show', icon: 'eye' }
            - { name: 'edit', icon: 'edit' }
            - { name: 'delete', icon: 'remove' }
    entities:
        Asignatura:
            class: AppBundle\Entity\Asignatura
            form:
                fields:
                    - 'id'
                    - 'nombre'

        Dependencia:
            class: AppBundle\Entity\Dependencia

        Elemento:
            class: AppBundle\Entity\Elemento
            form:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - 'fechaIngreso'
                    - 'estado'
                    - 'tipo'
                    - 'tipoPrestamo'
                    - 'observaciones'
                    - 'lugar'
                    - 'equipo'
                    - 'activo'

        Equipo:
            class: AppBundle\Entity\Equipo

        Facultad:
            class: AppBundle\Entity\Facultad
            form:
                fields:
                    - 'nombre'

        Lugar:
            class: AppBundle\Entity\Lugar
            form:
                fields:
                    - 'nombre'
                    - 'cantidadEquipos'
                    - 'descripcion'
                    - 'visible'

        ProyectoCurricular:
            class: AppBundle\Entity\ProyectoCurricular
            form:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'facultad'

        Usuario:
            class: AppBundle\Entity\Usuario
            form:
                fields:
                    - 'id'
                    - 'codigo'
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'password'
                    - { property: 'rol', type: 'choice', type_options: { choices:  { 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_FUNCIONARIO': 'ROLE_FUNCIONARIO', 'ROLE_DOCENTE': 'ROLE_DOCENTE', 'ROLE_ESTUDIANTE': 'ROLE_ESTUDIANTE',  } } }
                    - 'cargo'
                    - 'estado'
                    - 'dependencia'
                    - 'proyectoCurricular'
                    - 'activo'


