# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path:  usuario_login
                check_path:  usuario_login_check
                use_referer: true
            logout:
                path:        usuario_logout
            remember_me:
                secret:      "%secret%"
                lifetime:    28800

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        - { path: ^/registro/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/perfil/*, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/efconnect, role: ROLE_ADMIN }
        - { path: ^/elfinder, role: ROLE_ADMIN }
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        usuarios:
            entity: { class: AppBundle\Entity\Usuario, property: documento }

    encoders:
        AppBundle\Entity\Usuario: bcrypt
