# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.calendar_listener:
        class: AppBundle\EventListener\CalendarEventListener
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
        arguments: ['@doctrine.orm.entity_manager', '@router']

    admin.facultad:
        class: AppBundle\Admin\FacultadAdmin
        arguments: [~, AppBundle\Entity\Facultad, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Facultad }

    admin.dependencia:
            class: AppBundle\Admin\DependenciaAdmin
            arguments: [~, AppBundle\Entity\Dependencia, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Dependencia }