easy_admin:
    entities:
        Asignatura:
            class: AppBundle\Entity\Asignatura
            list:
                title: 'Asignaturas'
            form:
                fields:
                    - 'id'
                    - 'nombre'
