easy_admin:
    site_name: 'UD'

    formats:
        date:     'd-m-Y'
        time:     'H:i'
        datetime: 'd-m-Y H:i:s'

    list:
        actions:
            - { name: 'show', icon: 'eye' }
            - { name: 'edit', icon: 'edit' }
            - { name: 'delete', icon: 'remove' }

    design:
        color_scheme: 'light'

        menu:
            - { label: 'Inicio', icon: 'home', route: 'index' }
            - { entity: 'Asignatura', icon: 'book', label: 'Asignaturas' }
            - { entity: 'Dependencia', label: 'Dependencias' }
            - { entity: 'Elemento', icon: 'plug', label: 'Elementos' }
            - { entity: 'ElementoPerdido', icon: 'search', label: 'Elementos Perdidos' }
            - { entity: 'Equipo', icon: 'desktop', label: 'Equipos' }
            - { entity: 'Facultad', icon: 'university', label: 'Facultades' }
            - { entity: 'Lugar', label: 'Lugares' }
            - { entity: 'Mantenimiento', icon: 'wrench', label: 'Mantenimientos' }
            - { entity: 'MantenimientoExterno', icon: 'wrench', label: 'Mantenimientos Externos' }
            - { entity: 'ProyectoCurricular',label: 'Proyectos Curriculares' }
            - { entity: 'Usuario', icon: 'users', label: 'Usuarios' }
