easy_admin:
    site_name: 'UD'

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i'

    list:
        actions:
            - { name: 'show', icon: 'eye' }
            - { name: 'edit', icon: 'edit' }
            - { name: 'delete', icon: 'remove' }

    design:
        color_scheme: 'light'

        menu:
            - { label: 'Inicio', icon: 'home', route: 'index' }
            - { entity: 'Asignatura', icon: 'book', label: 'Asignaturas' }
            - { entity: 'Dependencia', icon: 'phone', label: 'Dependencias' }
            - label: 'Documentos'
              icon: 'file-text'
              children:
                - { entity: 'Documento', icon: 'file', label: 'Documentos' }
                - { entity: 'TipoDocumento', icon: 'tag', label: 'Tipos de Documentos' }
            - { entity: 'Evento', icon: 'calendar-o', label: 'Eventos' }
            - { entity: 'Facultad', icon: 'university', label: 'Facultades' }
            - { entity: 'Horario', icon: 'calendar', label: 'Horario' }
            - { entity: 'Incidencia', icon: 'exclamation-triangle', label: 'Incidencias' }
            - { entity: 'Lugar', icon: 'map-marker', label: 'Lugares' }
            - { entity: 'Mantenimiento', icon: 'wrench', label: 'Mantenimientos' }
            - { entity: 'MantenimientoExterno', icon: 'bug', label: 'Mantenimientos Externos' }
            - { entity: 'ProyectoCurricular', icon: 'graduation-cap', label: 'Proyectos Curriculares' }
            - { entity: 'Usuario', icon: 'users', label: 'Usuarios' }
            - label: 'Inventario'
              icon: ''
              children:
                - { entity: 'Baja' }
                - { entity: 'MotivoBaja' }
                - { entity: 'Elemento', icon: 'plug', label: 'Elementos' }
                - { entity: 'Equipo', icon: 'desktop', label: 'Equipos' }
                - { entity: 'Traslado' }
                - { entity: 'ObjetoEncontrado', icon: 'search', label: 'Objetos Encontrados' }
            - label: 'Prestamos'
              icon: ''
              children:
                - { entity: 'PrestamoElemento' }
                - { entity: 'PrestamoPracticaLibre' }
