easy_admin:
    entities:
        Dependencia:
            class: AppBundle\Entity\Dependencia

            list:
                title: 'Dependencias'
                sort: ['codigo', 'ASC']
                fields:
                    - 'codigo'
                    - 'nombre'
                    - 'facultad'

            edit:
                title: 'Modificar Dependencia'

            show:
                title: 'Dependencia'
                fields:
                    - 'codigo'
                    - 'nombre'
                    - 'facultad'
