easy_admin:
    entities:
        Dependencia:
            class: AppBundle\Entity\Dependencia
            list:
                title: 'Dependencias'
            form:
                fields:
                    - 'nombre'
                    - 'facultad'