easy_admin:
    entities:
        Dependencia:
            class: AppBundle\Entity\Dependencia
            list:
                title: 'Dependencias'
                fields:
                    - 'id'
                    - 'nombre'
                    - { property: 'facultad.nombre', label: 'Facultad', sortable: true }
            form:
                fields:
                    - 'nombre'
                    - { property: 'facultad', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Facultad' } }