easy_admin:
    entities:
        Documento:
            class: AppBundle\Entity\Documento
            controller: AppBundle\Controller\DocumentoController

            show:
                fields:
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'usuarioSube', label: 'Subido por' }
                    - { property: 'archivo', template: 'archivo.html.twig', base_path: '%app.path.documentos%' }
                    - { property: 'fechaSubida', label: 'Fecha de subida' }

            list:
                title: 'Documentos'
                fields:
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'usuarioSube', label: 'Subido por' }
                    - { property: 'archivo', template: 'archivo.html.twig', base_path: '%app.path.documentos%' }
                    - { property: 'fechaSubida', label: 'Fecha de subida' }
                sort: ['fechaSubida', 'DESC']

            form:
                fields:
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'archivoFile', type: 'vich_file', label: 'Archivo' }

        TipoDocumento:
            class: AppBundle\Entity\TipoDocumento

            list:
                title: 'Tipos de Documento'
                sort: ['nombre', 'ASC']
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Tipo de Documento' }
                fields:
                    - 'nombre'
                    - 'documentos'

            show:
                title: 'Tipo de Documento (#%%entity_id%%)'
                fields:
                    - 'nombre'
                    - 'documentos'

            form:
                fields:
                    - 'nombre'
            new:
                title: 'Crear Tipo de Documento'

            edit:
                title: 'Modificar Tipo de Documento'

