easy_admin:
    entities:
        Documento:
            class: AppBundle\Entity\Documento
            controller: AppBundle\Controller\DocumentoController
            show:
                fields:
                    - 'id'
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'usuario', label: 'Subido por' }
                    - { property: 'archivo', template: 'archivo.html.twig', base_path: '%app.path.documentos%' }
                    - { property: 'fechaSubida', label: 'Fecha de subida' }
            list:
                title: 'Documentos'
                fields:
                    - 'id'
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'usuario', label: 'Subido por' }
                    - { property: 'archivo', template: 'archivo.html.twig', base_path: '%app.path.documentos%' }
                    - { property: 'fechaSubida', label: 'Fecha de subida' }
            form:
                fields:
                    - 'nombre'
                    - { property: 'tipoDocumento', label: 'Tipo de documento' }
                    - { property: 'archivoFile', type: 'vich_file', label: 'Archivo' }

        TipoDocumento:
            class: AppBundle\Entity\TipoDocumento
            list:
                title: 'Tipos de Documento'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Tipo de Documento' }
            new:
                title: 'Crear Tipo de Documento'
            edit:
                title: 'Modificar Tipo de Documento'
            show:
                title: 'Tipo de Documento (#%%entity_id%%)'
            form:
                fields:
                    - 'nombre'