easy_admin:
    entities:
        ElementoPerdido:
            class: AppBundle\Entity\ElementoPerdido
            controller: AppBundle\Controller\ElementoPerdidoController
            list:
                title: 'Elementos Perdidos'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Elemento Perdido' }
                fields:
                   - 'id'
                   - 'descripcion'
                   - 'lugar'
                   - 'fechaRegistro'
                   - { property: 'entregado', type: 'boolean' }
                   - 'fechaEntrega'
            show:
                title: 'Elemento Perdido (#%%entity_id%%)'
                fields:
                   - 'id'
                   - 'descripcion'
                   - 'lugar'
                   - 'fechaRegistro'
                   - 'usuarioRegistra'
                   - 'entregado'
                   - 'fechaEntrega'
                   - 'usuarioEntrega'
            form:
               fields:
                   - 'descripcion'
                   - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
                   - 'entregado'
            new:
                title: 'Crear Elemento Perdido'
            edit:
                title: 'Modificar Elemento Perdido'
                
