easy_admin:
    entities:
        Elemento:
            class: AppBundle\Entity\Elemento
            list:
                title: 'Elementos'
            form:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - 'fechaIngreso'
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Bueno': 'Bueno', 'Dañado': 'Dañado', 'Otro': 'Otro' } } }
                    - { property: 'tipo', type: 'choice', type_options: { choices:  { 'Computador': 'Computador', 'Especializado': 'Especializado', 'Otro': 'Otro' } } }
                    - { property: 'restriccionPrestamo', type: 'choice', type_options: { choices:  { 'Funcionario': 'Funcionario' } } }
                    - 'observaciones'
                    - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
                    - { property: 'equipo', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Equipo' } }
                    - 'activo'