easy_admin:
    entities:
        Elemento:
            class: AppBundle\Entity\Elemento
            list:
                title: 'Elementos'
                fields:
                    - 'id'
                    - 'nombre'
                    - 'serial'
                    - 'fechaIngreso'
                    - 'estado'
                    - 'restriccionPrestamo'
                    - 'lugar'
                    - { property: 'activo', type: 'boolean' }

            show:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - 'fechaIngreso'
                    - 'estado'
                    - 'restriccionPrestamo'
                    - 'observaciones'
                    - 'lugar'
                    - 'activo'
                    - 'equipo'

            form:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - 'fechaIngreso'
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Bueno': 'Bueno', 'Dañado': 'Dañado', 'Otro': 'Otro' } } }
                    - { property: 'restriccionPrestamo', type: 'choice', type_options: { choices:  { 'Funcionario': 'Funcionario' } } }
                    - 'observaciones'
                    - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
                    - { property: 'equipo', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Equipo' } }
                    - { property: 'activo', type: 'checkbox', type_options: { data: true }}