easy_admin:
    entities:
        Elemento:
            class: AppBundle\Entity\Elemento
            controller: AppBundle\Controller\ElementoController

            list:
                title: 'Elementos'
                fields:
                    - 'placa'
                    - 'nombre'
                    - 'serial'
                    - { property: 'fechaIngreso', type: 'date' }
                    - 'estado'
                    - 'tipoPrestamo'
                    - 'lugar'
                    - { property: 'prestado', type: 'boolean' }
                    - { property: 'activo', type: 'boolean' }
                sort: 'placa'

            show:
                fields:
                    - 'placa'
                    - 'nombre'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - { property: 'fechaIngreso', type: 'date' }
                    - 'estado'
                    - 'tipoPrestamo'
                    - 'observaciones'
                    - 'lugar'
                    - 'prestado'
                    - 'activo'
                    - 'equipo'

            form:
                fields:
                    - 'placa'
                    - 'nombre'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
                    - { property: 'fechaIngreso', type: 'date', type_options: { widget: 'single_text', html5: false } }
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Bueno': 'Bueno', 'Mantenimiento': 'Mantenimiento', Dañado': 'Dañado', 'Otro': 'Otro' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'tipoPrestamo', type: 'choice', type_options: { choices:  { 'Todos': 'Todos', 'Funcionarios': 'Funcionarios', 'Nadie': 'Nadie' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'equipo', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Equipo' } }
                    - 'observaciones'
                    - { property: 'activo', type: 'checkbox' }
