easy_admin:
    entities:
        Elemento:
            class: AppBundle\Entity\Elemento
            controller: AppBundle\Controller\ElementoController

            list:
                title: 'Elementos'
                fields:
                    - 'placa'
                    - 'serial'
                    - 'estado'
                    - 'tipo'
                    - 'tipoPrestamo'
                    - 'lugar'
                    - 'equipo'
                    - { property: 'prestado', type: 'boolean' }
                    - { property: 'activo', type: 'boolean' }
                sort: 'placa'

            show:
                fields:
                    - 'placa'
                    - 'modelo'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - 'tipo'
                    - 'lugar'
                    - 'equipo'
                    - { property: 'fechaIngreso', type: 'date' }
                    - 'estado'
                    - 'tipoPrestamo'
                    - { property: 'observaciones', type: 'raw' }
                    - 'prestado'
                    - 'activo'

            form:
                fields:
                    - 'placa'
                    - 'modelo'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - { property: 'lugar', type: 'entity', type_options: { class: 'AppBundle\Entity\Lugar', attr: { 'data-widget': 'select2' } } }
                    - { property: 'equipo', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Equipo' } }
                    - { property: 'fechaIngreso', type: 'date', type_options: { widget: 'single_text', html5: false } }
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Bueno': 'Bueno', 'Mantenimiento': 'Mantenimiento', Dañado': 'Dañado', 'Malo': 'Malo', 'Otro': 'Otro' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'tipo', type_options: { attr: { placeholder: 'CPU, Teclado, Monitor' } } }
                    - { property: 'tipoPrestamo', type: 'choice', type_options: { choices:  {  'Nadie': 'Nadie', 'Funcionarios': 'Funcionarios', 'Todos': 'Todos' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'observaciones', type: 'ckeditor' }
                    - { property: 'activo', type: 'checkbox' }
