easy_admin:
    entities:
        ElementoPerdido:
            class: AppBundle\Entity\ElementoPerdido
            controller: AppBundle\Controller\ElementoPerdidoController
            list:
                title: 'Elementos Perdidos'
                fields:
                   - 'id'
                   - 'descripcion'
                   - 'fechaRegistro'
                   - 'estado'
                   - 'fechaEntrega'
                   - 'lugar'
            form:
               fields:
                   - 'descripcion'
                   - { property: 'estado', type: 'choice', type_options: { choices:  { 'Disponible': 'Disponible', 'Entregado': 'Entregado', } } }
                   - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
