easy_admin:
    entities:
        Elemento:
            class: AppBundle\Entity\Elemento
            list:
                title: 'Elementos'
            form:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'marca'
                    - 'descripcion'
                    - 'serial'
                    - 'fechaIngreso'
                    - 'estado'
                    - 'tipo'
                    - 'tipoPrestamo'
                    - 'observaciones'
                    - 'lugar'
                    - 'equipo'
                    - 'activo'