easy_admin:
    entities:
        ElementoPerdido:
            class: AppBundle\Entity\ElementoPerdido
            controller: AppBundle\Controller\ElementoPerdidoController
            list:
                title: 'Elementos Perdidos'
                fields:
                   - 'id'
                   - 'descripcion'
                   - 'lugar'
                   - 'fechaRegistro'
                   - { property: 'entregado', type: 'boolean' }
                   - 'fechaEntrega'

            show:
                fields:
                   - 'id'
                   - 'descripcion'
                   - 'lugar'
                   - 'fechaRegistro'
                   - 'usuarioRegistra'
                   - 'entregado'
                   - 'fechaEntrega'
                   - 'usuarioEntrega'

            form:
               fields:
                   - 'descripcion'
                   - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
                   - 'entregado'
