easy_admin:
    entities:
        Equipo:
            class: AppBundle\Entity\Equipo
            list:
                title: 'Equipos'
                sort: 'nombre'
            form:
                fields:
                    - 'nombre'
                    - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
                    - { property: 'elementos', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Elemento', by_reference: false } }
