easy_admin:
    entities:
        Equipo:
            class: AppBundle\Entity\Equipo
            controller: AppBundle\Controller\EquipoController

            list:
                title: 'Equipos'
                sort: 'nombre'
                fields:
                    - { property: 'nombre' }
                    - { property: 'lugar' }
                    - { property: 'prestado', type: 'boolean' }
                    - { property: 'elementos' }

            show:
                fields:
                    - { property: 'nombre' }
                    - { property: 'lugar' }
                    - { property: 'prestado', type: 'boolean' }
                    - { property: 'elementos' }

            new:
                fields:
                    - 'nombre'
                    - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
                    - { property: 'elementos', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Elemento', by_reference: false } }

            edit:
                fields:
                    - { property: 'nombre', type: 'text', type_options: { read_only: true } }
                    - { property: 'lugar', type: 'text', type_options: { read_only: true } }
                    - { property: 'elementos', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Elemento', by_reference: false } }
