easy_admin:
    entities:
        Facultad:
            class: AppBundle\Entity\Facultad

            list:
                title: 'Facultades'

            show:
                fields:
                    - 'nombre'
                    - 'dependencias'
                    - 'proyectosCurriculares'

            form:
                fields:
                    - 'nombre'
