easy_admin:
    entities:
        Incidencia:
            class: AppBundle\Entity\Incidencia
            controller: AppBundle\Controller\IncidenciaController

            list:
                title: 'Incidencias'
                fields:
                    - { property: 'fechaRegistro', type: 'datetime', label: 'Fecha de registro' }
                    - { property: 'descripcion', type: 'raw', css_class: 'col-sm-3'}
                    - { property: 'estado' }
                    - { property: 'fechaAtencion', type: 'datetime', label: 'Fecha de atención' }
                    - { property: 'usuarioRegistra', label: 'Usuario que registra' }
                    - { property: 'usuarioAtiende', label: 'Usuario que atiende' }
                sort: 'fechaRegistro'

            show:
                fields:
                    - { property: 'fechaRegistro', type: 'datetime', label: 'Fecha de registro' }
                    - { property: 'descripcion', type: 'raw' }
                    - { property: 'estado' }
                    - { property: 'fechaAtencion', type: 'datetime', label: 'Fecha de atención' }
                    - { property: 'usuarioRegistra', label: 'Usuario que registra' }
                    - { property: 'usuarioAtiende', label: 'Usuario que atiende' }
            form:
                fields:
                    - { property: 'fechaRegistro', type: 'datetime', label: 'Fecha de registro', type_options: { widget: 'single_text' } }
                    - { property: 'descripcion', type: 'ckeditor' }
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Sin Atender': 'Sin Atender', 'Atendida': 'Atendida' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'fechaAtencion', type: 'datetime', label: 'Fecha de atención', type_options: { widget: 'single_text' } }
                    - { property: 'usuarioAtiende', type: 'easyadmin_autocomplete', label: 'Usuario que atiende', type_options: { class: 'AppBundle\Entity\Usuario' } }
