easy_admin:
    entities:
        Mantenimiento:
            class: AppBundle\Entity\Mantenimiento
            list:
                title: 'Mantenimientos'
#            form:
#                fields:
#                    - 'nombre'
#                    - 'cantidadEquipos'
#                    - 'descripcion'
#                    - 'visible'