easy_admin:
    entities:
        MantenimientoExterno:
            class: AppBundle\Entity\MantenimientoExterno
            list:
                title: 'Mantenimientos Externos'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Mantenimiento Externo' }
            new:
                title: 'Crear Mantenimiento Externo'
            edit:
                title: 'Modificar Mantenimiento Externo'
            show:
                title: 'Mantenimiento Externo (#%%entity_id%%)'
            form:
                fields:
                    - 'nombreEmpresa'
                    - 'nombreTecnico'
                    - 'cedulaTecnico'
                    - { property: 'fecha', type: 'datetime', type_options: { widget: 'single_text' } }
                    - 'descripcion'
                    - { property: 'usuarioAtiende', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Usuario' } }