easy_admin:
    entities:
        ObjetoEncontrado:
            class: AppBundle\Entity\ObjetoEncontrado
            controller: AppBundle\Controller\ObjetoEncontradoController
            list:
                title: 'Objetos Encontrados'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Objeto Encontrado' }
                fields:
                   - 'id'
                   - 'descripcion'
                   - 'lugar'
                   - 'fechaRegistro'
                   - { property: 'entregado', type: 'boolean' }
                   - 'fechaEntrega'
            show:
                title: 'Objeto Encontrado (#%%entity_id%%)'
                fields:
                   - 'id'
                   - 'descripcion'
                   - 'lugar'
                   - 'fechaRegistro'
                   - 'usuarioRegistra'
                   - 'entregado'
                   - 'fechaEntrega'
                   - 'usuarioEntrega'
            form:
               fields:
                   - 'descripcion'
                   - { property: 'lugar', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Lugar' } }
                   - 'entregado'
            new:
                title: 'Crear Objeto Encontrado'
            edit:
                title: 'Modificar Objeto Encontrado'
                
