easy_admin:
    entities:
        ObjetoEncontrado:
            class: AppBundle\Entity\ObjetoEncontrado
            controller: AppBundle\Controller\ObjetoEncontradoController

            list:
                title: 'Objetos Encontrados'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Objeto Encontrado' }
                fields:
                    - 'id'
                    - 'descripcion'
                    - 'lugar'
                    - { property: 'fechaRegistro', label: 'Fecha de registro' }
                    - { property: 'entregado', type: 'boolean' }
                    - { property: 'fechaEntrega', label: 'Fecha de entrega' }

            show:
                title: 'Objeto Encontrado (#%%entity_id%%)'
                fields:
                    - 'id'
                    - 'descripcion'
                    - 'lugar'
                    - { property: 'fechaRegistro', label: 'Fecha de registro' }
                    - { property: 'usuarioRegistra', label: 'Registrado por' }
                    - 'entregado'
                    - { property: 'usuarioReclama', label: 'Entregado a' }
                    - { property: 'fechaEntrega', label: 'Fecha de entrega' }
                    - { property: 'usuarioEntrega', label: 'Entregado por' }

            form:
               fields:
                    - 'descripcion'
                    - { property: 'fechaRegistro', type: 'datetime', label: 'Fecha de registro', type_options: { widget: 'single_text' } }
                    - { property: 'lugar', type: 'entity', type_options: { class: 'AppBundle\Entity\Lugar', attr: { 'data-widget': 'select2' } } }
                    - 'entregado'
                    - { property: 'usuarioReclama', type: 'easyadmin_autocomplete', label: 'Entregado a', type_options: { class: 'AppBundle\Entity\Usuario' } }

            new:
                title: 'Crear Objeto Encontrado'

            edit:
                title: 'Modificar Objeto Encontrado'
