easy_admin:
    entities:
        PrestamoPracticaLibre:
            class: AppBundle\Entity\PrestamoPracticaLibre
#            list:
#                title: 'Dependencias'
#            form:
#                fields:
#                    - 'nombre'
#                    - { property: 'facultad', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Facultad' } }
