easy_admin:
    entities:
        ProyectoCurricular:
            class: AppBundle\Entity\ProyectoCurricular
            form:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'facultad'