easy_admin:
    entities:
        ProyectoCurricular:
            class: AppBundle\Entity\ProyectoCurricular
            list:
                title: 'Proyectos Curriculares'
            form:
                fields:
                    - 'id'
                    - 'nombre'
                    - 'facultad'