easy_admin:
    entities:
        ProyectoCurricular:
            class: AppBundle\Entity\ProyectoCurricular

            list:
                title: 'Proyectos Curriculares'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Proyecto Curricular' }
                fields:
                    - { property: 'id', type: 'text' }
                    - 'nombre'
                    - 'facultad'

            form:
                fields:
                    - { property: 'id', type: 'integer' }
                    - 'nombre'
                    - 'facultad'

            new:
                title: 'Crear Proyecto Curricular'

            edit:
                title: 'Modificar Proyecto Curricular'

            show:
                title: 'Proyecto Curricular'
                fields:
                    - 'id'
                    - 'nombre'
                    - 'facultad'
