easy_admin:
    entities:
        ProyectoCurricular:
            class: AppBundle\Entity\ProyectoCurricular
            list:
                title: 'Proyectos Curriculares'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Proyecto Curricular' }
            new:
                title: 'Crear Proyecto Curricular'
            edit:
                title: 'Modificar Proyecto Curricular'
            show:
                title: 'Proyecto Curricular (#%%entity_id%%)'
            
                