easy_admin:
    entities:
        SolicitudSala:
            class: AppBundle\Entity\SolicitudSala
            controller: AppBundle\Controller\SolicitudSalaController
            disabled_actions: ['new']

            list:
                title: 'Solicitudes de Sala'
                fields:
                    - { property: 'fecha', type: 'date' }
                    - { property: 'horaInicio', type: 'time' }
                    - { property: 'horaFin', type: 'time' }
                    - { property: 'fechaSolicitud', type: 'datetime', label: 'Fecha de solicitud' }
                    - { property: 'usuarioRealiza', label: 'Usuario que realiza' }
                    - { property: 'estado' }
                    - { property: 'lugar' }
                    - { property: 'fechaRespuesta', type: 'datetime', label: 'Fecha de respuesta' }
                sort: 'fechaSolicitud'

            show:
                title: 'Solicitud de Sala'
                fields:
                    - { property: 'fecha', type: 'date' }
                    - { property: 'horaInicio', type: 'time' }
                    - { property: 'horaFin', type: 'time' }
                    - { property: 'fechaSolicitud', type: 'datetime', label: 'Fecha de solicitud' }
                    - { property: 'estado' }
                    - { property: 'usuarioRealiza', label: 'Usuario que realiza' }
                    - { property: 'lugar' }
                    - { property: 'observaciones', type: 'raw' }
                    - { property: 'fechaRespuesta', type: 'datetime', label: 'Fecha de respuesta' }
                    - { property: 'usuarioResponde', label: 'Usuario que responde' }

            edit:
                title: 'Modificar Solicitud de Sala'
                fields:
                    - { property: 'fecha', type: 'date', type_options: { widget: 'single_text', html5: false, disabled: true } }
                    - { property: 'horaInicio', type: 'time', type_options: { widget: 'single_text', disabled: true } }
                    - { property: 'horaFin', type: 'time', type_options: { widget: 'single_text', disabled: true } }
                    - { property: 'fechaSolicitud', type: 'datetime', label: 'Fecha de solicitud', type_options: { widget: 'single_text', disabled: true } }
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Pendiente': 'Pendiente', 'Aprobada': 'Aprobada' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'usuarioRealiza', label: 'Usuario que realiza', type_options: { disabled: true } }
                    - { property: 'lugar',  type_options: { disabled: true } }
                    - { property: 'observaciones', type: 'ckeditor', type_options: { disabled: true } }