easy_admin:
    entities:
        SolicitudSala:
            class: AppBundle\Entity\SolicitudSala
            controller: AppBundle\Controller\SolicitudSalaController
            disabled_actions: ['new']

            list:
                title: 'Solicitudes de Sala'
                fields:
                    - { property: 'fechaSolicitud', type: 'datetime', label: 'Fecha de solicitud' }
                    - { property: 'estado' }
                    - { property: 'fecha', type: 'date' }
                    - { property: 'horaInicio', type: 'time' }
                    - { property: 'horaFin', type: 'time' }
                    - { property: 'fechaRespuesta', type: 'datetime', label: 'Fecha de respuesta' }
                sort: 'fechaSolicitud'

            show:
                fields:
                    - { property: 'fechaSolicitud', type: 'datetime', label: 'Fecha de solicitud' }
                    - { property: 'estado' }
                    - { property: 'usuarioRealiza', label: 'Usuario que realiza' }
                    - { property: 'fecha', type: 'date' }
                    - { property: 'horaInicio', type: 'time' }
                    - { property: 'horaFin', type: 'time' }
                    - { property: 'lugar' }
                    - { property: 'observaciones', type: 'raw' }
                    - { property: 'fechaRespuesta', type: 'datetime', label: 'Fecha de respuesta' }
                    - { property: 'usuarioResponde', label: 'Usuario que responde' }

            edit:
                fields:
                    - { property: 'fechaSolicitud', type: 'datetime', label: 'Fecha de solicitud', type_options: { widget: 'single_text', disabled: true } }
                    - { property: 'estado' }
                    - { property: 'usuarioRealiza', label: 'Usuario que realiza', type_options: { disabled: true } }
                    - { property: 'fecha', type: 'date', type_options: { widget: 'single_text', disabled: true } }
                    - { property: 'horaInicio', type: 'time', type_options: { widget: 'single_text', disabled: true } }
                    - { property: 'horaFin', type: 'time', type_options: { widget: 'single_text', disabled: true } }
                    - { property: 'lugar' }
                    - { property: 'observaciones', type: 'ckeditor' }
                    - { property: 'fechaRespuesta', type: 'datetime', label: 'Fecha de respuesta' }
                    - { property: 'usuarioResponde', label: 'Usuario que responde' }