easy_admin:
    entities:
        SoporteFacultad:
            class: AppBundle\Entity\SoporteFacultad
            controller: AppBundle\Controller\SoporteFacultadController

            list:
                title: 'Soportes Facultad'
                actions:
                    - { name: 'show', icon: 'eye' }
                    - { name: 'new', label: 'Crear Préstamo Elemento' }
                fields:
                    - { property: 'fechaRegistro', type: 'datetime', label: 'Fecha de Registro' }
                    - { property: 'dependencia' }
                    - { property: 'descripcionProblema', type: 'raw', css_class: 'col-sm-2'}
                    - { property: 'usuarioRegistra', label: 'Usuario que Registra' }
                sort: 'fechaRegistro'

            show:
                title: 'Soporte Facultad'
                fields:
                    - { property: 'id' }
                    - { property: 'fechaRegistro', type: 'datetime', label: 'Fecha de Registro' }
                    - { property: 'dependencia' }
                    - { property: 'descripcionProblema', type: 'raw' }
                    - { property: 'usuarioRegistra', label: 'Usuario que Registra' }

            form:
                fields:
                    - { property: 'fechaRegistro', type: 'datetime', label: 'Fecha de Registro', type_options: { widget: 'single_text', html5: false } }
                    - { property: 'dependencia' }
                    - { property: 'descripcionProblema', type: 'ckeditor' }
                    - { property: 'usuarioRegistra', label: 'Usuario que Registra' }

            new:
                title: 'Nuevo Soporte Facultad'

            edit:
                title: 'Modificar Soporte Facultad'