easy_admin:
    entities:
        Usuario:
            class: AppBundle\Entity\Usuario
            controller: AppBundle\Controller\UsuarioController
            list:
                title: 'Usuarios'
                fields:
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'rol'
                    - 'activo'
                    - 'fechaCreacion'
                sort: 'fechaCreacion'
            show:
                fields:
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'rol'
                    - 'cargo'
                    - 'estado'
                    - 'dependencia'
                    - 'proyectoCurricular'
                    - 'activo'
                    - 'fechaCreacion'
            form:
                fields:
                    - 'documento'
                    - 'codigo'
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - { property: 'passwordEnClaro', type: 'repeated', type_options: { type: 'password', invalid_message: 'Las dos contraseñas deben coincidir', first_options: { label: 'Contraseña' }, second_options: { label: 'Confirmar Contraseña' }, required: false } }
                    - { property: 'rol', type: 'choice', type_options: { choices:  { 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_FUNCIONARIO': 'ROLE_FUNCIONARIO', 'ROLE_DOCENTE': 'ROLE_DOCENTE', 'ROLE_ESTUDIANTE': 'ROLE_ESTUDIANTE' }, attr: { 'data-widget': 'select2' } } }
                    - 'cargo'
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Paz y Salvo': 'Paz y Salvo', 'En Mora': 'En Mora' }, attr: { 'data-widget': 'select2' } } }
                    - 'dependencia'
                    - { property: 'proyectoCurricular', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\ProyectoCurricular' } }
                    - 'activo'
            new:
                form_options: { validation_groups: ['Default', 'New'] }

