easy_admin:
    entities:
        Usuario:
            class: AppBundle\Entity\Usuario
            controller: AppBundle\Controller\UsuarioController
            list:
                title: 'Usuarios'
                fields:
                    - { property: 'tipoDocumento' }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'rol'
                    - 'activo'
                    - 'fechaCreacion'
                sort: 'fechaCreacion'

            show:
                fields:
                    - { property: 'tipoDocumento' }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - 'rol'
                    - 'cargo'
                    - 'estado'
                    - 'dependencia'
                    - 'proyectoCurricular'
                    - 'activo'
                    - 'fechaCreacion'
            form:
                fields:
                    - { property: 'tipoDocumento', type: 'choice', type_options: { choices:  { 'Cédula de Ciudadanía': 'C.C.' , 'Tarjeta de Identidad': 'T.I.', 'Cédula de Extranjería': 'C.E.' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'documento', type: 'text' }
                    - { property: 'codigo', type: 'text' }
                    - 'nombre'
                    - 'apellido'
                    - 'email'
                    - { property: 'passwordEnClaro' }
                    - { property: 'rol', type: 'choice', type_options: { choices:  { 'ROLE_ESTUDIANTE': 'ROLE_ESTUDIANTE', 'ROLE_FUNCIONARIO': 'ROLE_FUNCIONARIO', 'ROLE_DOCENTE': 'ROLE_DOCENTE', 'ROLE_ADMIN': 'ROLE_ADMIN' }, attr: { 'data-widget': 'select2' } } }
                    - 'cargo'
                    - { property: 'estado', type: 'choice', type_options: { choices:  { 'Paz y Salvo': 'Paz y Salvo', 'En Mora': 'En Mora' }, attr: { 'data-widget': 'select2' } } }
                    - { property: 'dependencia', type: 'entity', type_options: { class: 'AppBundle\Entity\Dependencia', attr: { 'data-widget': 'select2' }, placeholder: 'Ninguna' } }
                    - { property: 'proyectoCurricular', type: 'entity', type_options: { class: 'AppBundle\Entity\ProyectoCurricular', attr: { 'data-widget': 'select2' }, placeholder: 'Ninguno' } }
                    - 'activo'
            edit:
                fields:
                    - { property: 'passwordEnClaro' }
